name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: windows-latest
    
    strategy:
      matrix:
        configuration: [Debug] 

    env:
      Solution_Name: StockManager.sln
      Test_Project_Path: StockManager.Tests\StockManager.Tests.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "console;verbosity=detailed" -v n
